spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.ddl-auto=update

# show sql
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#logging.level.root=DEBUG
