# ======= BASE DE DONNÉES =======
spring.datasource.url=jdbc:mysql://localhost:3306/mdd_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ======= JPA / HIBERNATE =======
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# ======= JWT =======
app.jwt.secret=c7f1d2a8b4e6f9c3d1a7b8e4f2c9d6a1
app.jwt.expiration=8640000

